#file with sample annotations:
metasheet: 'metasheet.csv'

#run name:
run: 'medips_run'

#number of iterations used for cross validation:
iterations: 100

#files used by MeDIPs for calucating CpG enrichment. To generate on the fly, set to ""
genome_relH: ref_files/bsgenome.hsapiens.ucsc.hg19_relH.rds
genome_GoGe: ref_files/bsgenome.hsapiens.ucsc.hg19_GoGe.rds

#bed file specifying regions to remove from consideration
blacklist: 'ref_files/hg19-blacklist.v2.bed'

#bed file specifying regions to exclude from the relative methylation score (rms) analysis
rms_exclude: 'ref_files/hg19-blacklist.v2_wbc.peaks.merged.bed'

#up-DMRs in training set must overlap with these - if set to '', will calculate from reference_case and reference_control samples in metasheet. If set to "none", will not restrict:
restrict_up: ''

#down-DMRs in training set must overlap with these - if set to '', will calculate from reference_case and reference_control samples in metasheet. If set to "none", will not 
restrict_down: ''

#Designate whether or not DMRs analysis is needed. If set to 0, the analysis will be skipped
DMRs: 0

#samples can be paired end fastq files or medips files. can theoretically mix these, but hasn't been tested
#FOR SINGLE-END samples
SAMPLE1:
 - /path/to/sample1.fastq.gz
 #FOR PAIRED-END samples--WARNING: DON'T mix single-end samples w/ paired-end
 SAMPLE1:
  - /path/to/sample1_R1.fastq.gz
  - /path/to/sample1_R2.fastq.gz
#SAMPLE2:
#ETC...

 

 
